name: CI/CD

on:
  push:
    branches:
      - master   # Установим акшн на мастер (на пуши и пр)
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Чекаутим репо
        uses: actions/checkout@v3

      - name: Простравляем JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 21

      - name: Билдим через мавен
        run: mvn clean install  # Строим проект через Maven

      - name: Запускаем тесты
        run: mvn test  # Запуск unit-тестов через Maven

  build-and-deploy:
    runs-on: ubuntu-latest
    needs: build  # Выполняется после успешного билда
    steps:
      - name: Чекаутим
        uses: actions/checkout@v3

      - name: Ставим Jdk
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 21

      - name: Сборка приложения через Maven сборщик
        run: mvn clean package 

      - name: Запуск приложения
        run: |
          java -jar target/*.jar &
          sleep 5

      - name: Деплой в рендер
        run: |
          curl --request POST \
          -H "Accept: application/json" \
          -H "Content-Type: application/json" \
          https://api.render.com/deploy/srv-ctokm78gph6c73d79j8g?key=PGp4DFIU2eU
